import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h2>Build: {process.env.NEXT_PUBLIC_COMMIT_SHA || 'dev'}</h2>
        {children}
      </body>
    </html>
  );
}
