import * as React from 'react';
import type { Metadata } from 'next';

/**
 * The root layout of the application. It wraps all pages and components.
 * It includes the HTML structure and global styles.
 */
import '@plarium/d2c-ui-theme/theme.shared.css';
import '@plarium/d2c-ui-theme/theme.light.css';
import '@plarium/d2c-ui-theme/theme.dark.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <h2>Build: {process.env.NEXT_PUBLIC_COMMIT_SHA || 'dev'}</h2>
        {children}
      </body>
    </html>
  );
}
